import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Viewport } from "next";
import { Poppins } from "next/font/google";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const poppins = Poppins({
  subsets:['latin'], 
  variable: '--font-sans',
  weight: ['400'],
  display: 'block'
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export const viewport: Viewport = {
  viewportFit: "cover",
};

export default async function RootLayout({ children,}: Readonly<{children: React.ReactNode;}>) {

  return (
    <html lang="en" className={cn("font-sans", poppins.variable)}>
      
      <body
        className={`${poppins.variable} ${poppins.variable} antialiased`}
      >
          {children}
      </body>
    </html>
  );
}
