import { ItemFields } from "./mock-item-fields" 

export const mockData: ItemFields[] = [
    { id: 1,
    name: "Adaptive Tray",
    condition: "Fair",
    description: "Missing a piece",
    size: "Medium",
    color: "Yellow",
    status: "Available",
    donor: "Stacy M.",
    image_url: "/adaptive-tray.jpg",
    qr_code_url: "To-do",
    created_at: "9/9/2026" }, 

    { id: 2,
    name: "Posterior Walker",
    condition: "Good",
    size: "Medium",
    color: "Blue",
    status: "Available",
    donor: "Ashley S.",
    image_url: "/posterior-walker.jpg",
    qr_code_url: "To-do",
    created_at: "9/10/2026" }, 

    { id: 3,
    name: "Item 3",
    condition: "OK",
    size: "Large",
    color: "Green",
    status: "In Processing",
    donor: "Ashley S.",
    image_url: "/posterior-walker.jpg",
    qr_code_url: "To-do",
    created_at: "9/10/2026" }, 

    { id: 4,
    name: "Item 4",
    condition: "Excellent",
    size: "Small",
    color: "Yellow",
    status: "Permanently Allocated",
    donor: "Ashley S.",
    image_url: "/adaptive-tray.jpg",
    qr_code_url: "To-do",
    created_at: "9/10/2026" }, 

    { id: 5,
    name: "Item 5",
    condition: "Good",
    size: "Medium",
    color: "Red",
    status: "Available",
    donor: "Ashley S.",
    image_url: "/posterior-walker.jpg",
    qr_code_url: "To-do",
    created_at: "9/10/2026" }, 

    { id: 6,
    name: "Item 6",
    condition: "OK",
    size: "XL",
    color: "Purple",
    status: "Available",
    donor: "Ashley S.",
    image_url: "/posterior-walker.jpg",
    qr_code_url: "To-do",
    created_at: "9/10/2026" }, 

    { id: 7,
    name: "Item 7",
    condition: "Good",
    size: "Medium",
    color: "Blue",
    status: "Available",
    donor: "Ashley S.",
    image_url: "/adaptive-tray.jpg",
    qr_code_url: "To-do",
    created_at: "9/10/2026" }, 

    { id: 8,
    name: "Item 8",
    condition: "Good",
    size: "XS",
    color: "Pink",
    status: "Available",
    donor: "Ashley S.",
    image_url: "/posterior-walker.jpg",
    qr_code_url: "To-do",
    created_at: "9/10/2026" }, 

    { id: 9,
    name: "Item 9",
    condition: "Excellent",
    size: "XS",
    color: "Silver",
    status: "Available",
    donor: "Ashley S.",
    image_url: "/posterior-walker.jpg",
    qr_code_url: "To-do",
    created_at: "9/10/2026" }, 

]