import { ItemFields } from "./mock-item-fields" 

export const mockData: ItemFields[] = [
    { id: 1,
    name: "Adaptive Tray",
    category: "Adaptive Tray",
    condition: "Broken/Missing Pieces",
    description: "Missing a piece on underside",
    size: "Medium",
    color: "Yellow",
    status: "Available",
    donor: "Stacy M.",
    image_url: "/adaptive-tray.jpg",
    qr_code_url: "To-do",
    created_at: "9/9/2026" }, 

    { id: 2,
    name: "Blue Posterior Walker",
    category: "Walker",
    subcategory: "Posterior",
    condition: "Good",
    size: "Medium",
    color: "Blue",
    status: "Available",
    donor: "Ashley S.",
    image_url: "/posterior-walker.jpg",
    qr_code_url: "To-do",
    created_at: "9/10/2026" }, 

    { id: 3,
    name: "Silver Manual Rigid Wheelchair",
    category: "Wheelchair",
    subcategory: "Manual Rigid",
    condition: "Excellent",
    size: "Large",
    color: "Green",
    status: "In Processing",
    donor: "Ashley S.",
    image_url: "/posterior-walker.jpg",
    qr_code_url: "To-do",
    created_at: "9/10/2026" }, 

    { id: 4,
    name: "Activity Chair",
    condition: "Needs Cleaning",
    category: "Activity Chair",
    size: "Small",
    color: "Yellow",
    status: "Permanently Allocated",
    donor: "Ashley S.",
    image_url: "/adaptive-tray.jpg",
    qr_code_url: "To-do",
    created_at: "9/10/2026" }, 

    { id: 5,
    name: "Item 5",
    category: "Gait Trainer",
    condition: "Good",
    size: "Medium",
    color: "Red",
    status: "Available",
    donor: "Ashley S.",
    image_url: "/posterior-walker.jpg",
    qr_code_url: "To-do",
    created_at: "9/10/2026" }, 

    { id: 6,
    name: "Item 6",
    category: "Adaptive Tricycle",
    condition: "Broken/Missing Pieces",
    size: "XL",
    color: "Purple",
    status: "Available",
    donor: "Ashley S.",
    image_url: "/posterior-walker.jpg",
    qr_code_url: "To-do",
    created_at: "9/10/2026" }, 

    { id: 7,
    name: "Item 7",
    category: "Forearm Crutches",
    condition: "Good",
    size: "Medium",
    color: "Blue",
    status: "Available",
    donor: "Ashley S.",
    image_url: "/adaptive-tray.jpg",
    qr_code_url: "To-do",
    created_at: "9/10/2026" }, 

    { id: 8,
    name: "Item 8",
    category: "Wheelchair",
    subcategory: "Sport",
    condition: "Excellent",
    size: "XS",
    color: "Pink",
    status: "Available",
    donor: "Ashley S.",
    image_url: "/posterior-walker.jpg",
    qr_code_url: "To-do",
    created_at: "9/10/2026" }, 

    { id: 9,
    name: "Item 9",
    category: "Wheelchair",
    subcategory: "Manual Folding",
    condition: "Acceptable",
    description: "Good for kids",
    size: "XS",
    color: "Silver",
    status: "Available",
    donor: "Ashley S.",
    image_url: "/posterior-walker.jpg",
    qr_code_url: "To-do",
    created_at: "9/10/2026" }, 

]